name: pipeline ci/cd - publish corban package

on:
  push:
    branches:
      - main
    paths:
      - 'Artifacts/Corban.Internal.AspNet/**'
      - 'Artifacts/Corban.Internal.Contracts/**'

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      corban_internal_aspnet: ${{ steps.filter.outputs.corban_internal_aspnet }}
      corban_internal_contracts: ${{ steps.filter.outputs.corban_internal_contracts }}

    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: debug changes
        run: |
          echo "aspnet: ${{ steps.filter.outputs.corban_internal_aspnet }}"
          echo "contracts: ${{ steps.filter.outputs.corban_internal_contracts }}"

      - name: show changed files
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: detect changed paths
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            corban_internal_aspnet:
              - 'Artifacts/Corban.Internal.AspNet/**'
            corban_internal_contracts:
              - 'Artifacts/Corban.Internal.Contracts/**'

  # publish this package if there are changes in the corresponding path
  publish-corban-internal-aspnet:
    needs: changes
    if: needs.changes.outputs.corban_internal_aspnet == 'true'
    uses: ./.github/workflows/template-publish-package.yml
    with:
      working_directory: Artifacts/Corban.Internal.AspNet/Source
      dotnet_version: 10.0.x
      base_version: "1.0"
    secrets: inherit

  # publish this package if there are changes in the corresponding path
  publish-corban-internal-contracts:
    needs: changes
    if: needs.changes.outputs.corban_internal_contracts == 'true'
    uses: ./.github/workflows/template-publish-package.yml
    with:
      working_directory: Artifacts/Corban.Internal.Contracts/Source
      dotnet_version: 10.0.x
      base_version: "1.0"
    secrets: inherit
